window.games = [
  { name: "brotato", img: "/images/brotato.png", iframe: "games/brotato.html", identifier: "brotato", pin: true },
  { name: "celeste", img: "/images/celeste.png", iframe: "games/celeste.html", identifier: "celeste", pin: true },
  { name: "comments", img: "/images/comments.png", iframe: "games/comments.html", identifier: "comments" },
  { name: "deltarune", img: "/images/deltarune.png", iframe: "games/deltarune.html", identifier: "deltarune", pin: true },
  { name: "drive mad", img: "/images/drivemad.png", iframe: "games/drivemad.html", identifier: "drivemad" },
  { name: "fnaf 1", img: "/images/fnaf1.png", iframe: "games/fnaf1.html", identifier: "fnaf1" },
  { name: "friday night funkin'", img: "/images/fnftitle.png", iframe: "games/fnf/fnf.html", identifier: "fnf" },
  { name: "fnf: confronting yourself", img: "/images/fnfconfrontingyourself.png", iframe: "games/fnf/fnfconfrontingyourself.html", identifier: "fnfcy" },
  { name: "fnf: og", img: "/images/fnfog.png", iframe: "games/fnf/fnfog.html", identifier: "fnfog" },
  { name: "fnf: tainted fate", img: "/images/fnftaintedfate.png", iframe: "games/fnf/fnftaintedfate.html", identifier: "fnftf" },
  { name: "geometry dash", img: "/images/gd.png", iframe: "games/gd.html", identifier: "gd" },
  { name: "geometry dash lite", img: "/images/gdlite.png", iframe: "games/gdlite.html", identifier: "gdlite" },
  { name: "pizza tower", img: "/images/pizzatower.png", iframe: "games/pizzatower.html", identifier: "pizzatower", pin: true },
  { name: "retro bowl", img: "/images/retrobowl.png", iframe: "games/retrobowl.html", identifier: "retrobowl" },
  { name: "rocket goal", img: "/images/rocketgoal.png", iframe: "games/rocketgoal.html", identifier: "rocketgoal" },
  { name: "sonic cd", img: "/images/soniccd.png", iframe: "games/soniccd.html", identifier: "soniccd" },
  { name: "sonic mania", img: "/images/sonicmania.png", iframe: "games/sonicmania.html", identifier: "sonicmania" },
  { name: "superhot", img: "/images/superhot.png", iframe: "games/superhot.html", identifier: "superhot" },
  { name: "undertale", img: "/images/undertale.png", iframe: "games/undertale.html", identifier: "undertale", pin: true },
  { name: "cloudmoon", img: "/images/cloudmoon.png", iframe: "apps/cloudmoon.html", identifier: "cloudmoon", app: true },
  { name: "tiktok", img: "/images/tiktok.png", iframe: "apps/tiktok.html", identifier: "tiktok", app: true },
  { name: "Stickman Hook", img: "", iframe: "n/clstickmanhook.html", identifier: "stickmanhook" }
];
